-- Step 1 of supabase/SCHEMA_ROADMAP.md: listing_kind, status, condition grades.
--
-- HAND-WRITTEN, not generated by `db diff`. Two reasons:
--   1. The differ does not reliably capture RLS policies or grants, and this migration
--      replaces the products read policy (see supabase/README.md, "Caveats").
--   2. The backfill below is a judgement call the differ cannot make: every existing row
--      is assumed to be a second-hand item.
--
-- BEFORE APPLYING, see README.md "Known drift": local migration history does not match
-- remote. Confirm what the CLI intends to apply:
--   npx supabase migration list --linked
--   npx supabase db push --dry-run
--
-- MANUAL FOLLOW-UP REQUIRED. Existing rows are backfilled to condition_grade = 'good' as a
-- placeholder so the NOT NULL side of the CHECK can be satisfied. 'good' is a claim about
-- furniture nobody has inspected. Review every pre-existing product and correct its grade
-- before setting it to `available`; the backfill deliberately leaves them at `draft` so
-- nothing ships with an unverified condition claim.

begin;

-- ---------------------------------------------------------------------------
-- condition_grades
-- ---------------------------------------------------------------------------

create table if not exists "public"."condition_grades" (
    "code" "text" not null,
    "sort_order" smallint not null,
    "label_ka" "text" not null,
    "label_en" "text" not null,
    "description_ka" "text" default ''::"text" not null,
    constraint "condition_grades_code_check"
        check (("code" ~ '^[a-z][a-z0-9_]{1,30}$'::"text")),
    constraint "condition_grades_sort_order_check"
        check (("sort_order" >= 0)),
    constraint "condition_grades_label_ka_check"
        check ((("char_length"("btrim"("label_ka")) >= 2)
            and ("char_length"("label_ka") <= 80))),
    constraint "condition_grades_label_en_check"
        check ((("char_length"("btrim"("label_en")) >= 2)
            and ("char_length"("label_en") <= 80))),
    constraint "condition_grades_description_ka_check"
        check (("char_length"("description_ka") <= 500))
);

alter table "public"."condition_grades" owner to "postgres";

alter table only "public"."condition_grades"
    add constraint "condition_grades_pkey" primary key ("code");

alter table only "public"."condition_grades"
    add constraint "condition_grades_sort_order_key" unique ("sort_order");

insert into "public"."condition_grades"
    ("code", "sort_order", "label_ka", "label_en", "description_ka")
values
    ('as_new',      0, 'როგორც ახალი',     'As new',
        'გამოუყენებელი ან ახლისგან განურჩეველი. ხილული დაზიანების გარეშე.'),
    ('excellent',   1, 'შესანიშნავი',       'Excellent',
        'მინიმალური, ძნელად შესამჩნევი ცვეთა. სტრუქტურულად უნაკლო.'),
    ('good',        2, 'კარგი',             'Good',
        'ხილული, მაგრამ ჩვეულებრივი ცვეთა. სრულად ფუნქციური და მდგრადი.'),
    ('fair',        3, 'დამაკმაყოფილებელი', 'Fair',
        'მნიშვნელოვანი ესთეტიკური ცვეთა. ფუნქციურად გამართული.'),
    ('restoration', 4, 'აღსადგენი',         'For restoration',
        'საჭიროებს რესტავრაციას. იყიდება არსებული მდგომარეობით.')
on conflict ("code") do nothing;

-- ---------------------------------------------------------------------------
-- products: new columns
-- ---------------------------------------------------------------------------

-- Added without the CHECK constraints first, so existing rows can be backfilled before
-- anything is validated against them.
alter table "public"."products"
    add column if not exists "listing_kind" "text" default 'used_unique'::"text" not null,
    add column if not exists "status" "text" default 'draft'::"text" not null,
    add column if not exists "condition_grade" "text",
    add column if not exists "condition_summary" "text",
    add column if not exists "stock_quantity" integer;

-- ---------------------------------------------------------------------------
-- Backfill
-- ---------------------------------------------------------------------------

-- Every pre-existing row predates the used/new distinction. The shop is primarily
-- second-hand, so `used_unique` is the safe assumption: it is the branch that DEMANDS
-- documentation rather than the one that waives it. Guessing `new_stocked` would let an
-- undocumented used item pass every constraint in this file.
update "public"."products"
set "listing_kind" = 'used_unique'
where "listing_kind" is distinct from 'used_unique';

-- Placeholder grade. See the MANUAL FOLLOW-UP note at the top of this file.
update "public"."products"
set "condition_grade" = 'good'
where "condition_grade" is null;

-- `used_unique` rows must not carry a quantity.
update "public"."products"
set "stock_quantity" = null
where "listing_kind" = 'used_unique'
  and "stock_quantity" is not null;

-- Existing rows were publicly visible before this migration, and the new default is
-- `draft`, which would hide the entire catalog. They are moved to `available` so the
-- storefront does not go dark on deploy.
--
-- NOTE: this publishes rows carrying the placeholder grade above. If you would rather the
-- catalog go dark until every item is reviewed, delete this statement — the `draft`
-- default then holds and you publish each item by hand.
update "public"."products"
set "status" = 'available'
where "status" = 'draft';

-- ---------------------------------------------------------------------------
-- products: constraints, foreign key and indexes
-- ---------------------------------------------------------------------------

alter table "public"."products"
    add constraint "products_listing_kind_check"
        check (("listing_kind" = any (array[
            'used_unique'::"text", 'new_stocked'::"text"]))),
    add constraint "products_status_check"
        check (("status" = any (array[
            'draft'::"text", 'available'::"text", 'reserved'::"text",
            'sold'::"text", 'archived'::"text"]))),
    add constraint "products_condition_summary_check"
        check (("char_length"("condition_summary") <= 2000)),
    add constraint "products_stock_quantity_check"
        check (("stock_quantity" >= 0)),
    add constraint "products_condition_matches_kind_check"
        check ((("listing_kind" = 'used_unique'::"text"
                and "condition_grade" is not null
                and "stock_quantity" is null)
            or ("listing_kind" = 'new_stocked'::"text"
                and "condition_grade" is null
                and "condition_summary" is null
                and "stock_quantity" is not null)));

alter table only "public"."products"
    add constraint "products_condition_grade_fkey"
    foreign key ("condition_grade") references "public"."condition_grades"("code")
    on update cascade on delete restrict;

create index if not exists "products_available_created_at_idx"
    on "public"."products" using "btree" ("created_at" desc)
    where ("status" = 'available'::"text");

create index if not exists "products_available_category_id_idx"
    on "public"."products" using "btree" ("category_id", "created_at" desc)
    where ("status" = 'available'::"text");

-- ---------------------------------------------------------------------------
-- Grants and RLS
-- ---------------------------------------------------------------------------

-- Revoked before granting, for the reason documented at length in
-- schemas/07_grants_and_rls.sql: Supabase's default privileges leave a new table wide open
-- to anon, and `grant select` alone would not take that away.
revoke all on table "public"."condition_grades" from "anon";
revoke all on table "public"."condition_grades" from "authenticated";
grant select on table "public"."condition_grades" to "anon";
grant select, insert, update, delete on table "public"."condition_grades" to "authenticated";
grant all on table "public"."condition_grades" to "service_role";

alter table "public"."condition_grades" enable row level security;

create policy "Condition grades are publicly readable" on "public"."condition_grades"
    for select to "authenticated", "anon" using (true);

create policy "Permanent users can add condition grades" on "public"."condition_grades"
    for insert to "authenticated"
    with check (((( select "auth"."uid"() as "uid") is not null)
        and (coalesce((((select "auth"."jwt"() as "jwt") ->> 'is_anonymous'::"text"))::boolean, false) = false)));

create policy "Permanent users can edit condition grades" on "public"."condition_grades"
    for update to "authenticated"
    using (((( select "auth"."uid"() as "uid") is not null)
        and (coalesce((((select "auth"."jwt"() as "jwt") ->> 'is_anonymous'::"text"))::boolean, false) = false)))
    with check (((( select "auth"."uid"() as "uid") is not null)
        and (coalesce((((select "auth"."jwt"() as "jwt") ->> 'is_anonymous'::"text"))::boolean, false) = false)));

create policy "Permanent users can remove condition grades" on "public"."condition_grades"
    for delete to "authenticated"
    using (((( select "auth"."uid"() as "uid") is not null)
        and (coalesce((((select "auth"."jwt"() as "jwt") ->> 'is_anonymous'::"text"))::boolean, false) = false)));

-- Replaces the unconditional `using (true)` read policy. Draft and archived products stop
-- being readable with the publishable key; sold and reserved stay readable so their pages
-- keep working.
drop policy if exists "Products are publicly readable" on "public"."products";

create policy "Published products are publicly readable" on "public"."products"
    for select to "authenticated", "anon"
    using (("status" <> all (array['draft'::"text", 'archived'::"text"])));

commit;
