-- Baseline catalog schema.
--
-- Hand-authored from supabase/schemas/ in the order declared by [db.migrations]
-- schema_paths in config.toml. This is the creating migration the repo was missing:
-- production's history had it, this repo never captured it (see supabase/README.md
-- "Known drift"), so supabase/migrations/ held only the corrective grants change
-- and no local stack could start.
--
-- NOT generated by `db diff` or `db schema declarative sync`: db diff ignores
-- supabase/schemas entirely, and pg-delta's sync emitted table grants that give
-- anon INSERT/UPDATE/DELETE/TRUNCATE/MAINTAIN plus no CREATE EXTENSION. The
-- declarative files below are the production-captured source of truth; they are
-- concatenated verbatim so the grants and RLS policies stay exactly as written.
--
-- Timestamped before 20260911000000_tighten_image_table_grants.sql so that
-- corrective migration continues to apply on top of it.


-- ===========================================================================
-- schemas/01_extensions.sql
-- ===========================================================================

-- Extensions and non-public schemas.
-- Captured from production 2026-09-11 via `supabase db dump --linked`.

create schema if not exists "private";

alter schema "private" owner to "postgres";

create extension if not exists "pg_stat_statements" with schema "extensions";
create extension if not exists "pgcrypto" with schema "extensions";
create extension if not exists "supabase_vault" with schema "vault";
create extension if not exists "uuid-ossp" with schema "extensions";

-- ===========================================================================
-- schemas/02_categories.sql
-- ===========================================================================

-- Product catalogs. Referenced by products and category_images, so it loads first.
-- Captured from production 2026-09-11.

create table if not exists "public"."categories" (
    "id" "uuid" default "gen_random_uuid"() not null,
    "slug" "text" not null,
    "name" "text" not null,
    "description" "text" default ''::"text" not null,
    constraint "categories_description_check"
        check (("char_length"("description") <= 5000)),
    -- Slug allows Georgian letters and lowercase ASCII, hyphen-separated.
    constraint "categories_slug_check"
        check (((("char_length"("slug") >= 2) and ("char_length"("slug") <= 80))
            and ("slug" ~ '^[ა-ჰa-z0-9]+(-[ა-ჰa-z0-9]+)*$'::"text")))
);

alter table "public"."categories" owner to "postgres";

alter table only "public"."categories"
    add constraint "categories_pkey" primary key ("id");

alter table only "public"."categories"
    add constraint "categories_name_key" unique ("name");

alter table only "public"."categories"
    add constraint "categories_slug_key" unique ("slug");

-- ===========================================================================
-- schemas/03_products.sql
-- ===========================================================================

-- Products. Depends on categories.
-- Captured from production 2026-09-11.

create table if not exists "public"."products" (
    "id" "uuid" default "gen_random_uuid"() not null,
    "name" "text" not null,
    "description" "text" default ''::"text" not null,
    "price" numeric(12,2) not null,
    "category_id" "uuid" not null,
    "created_at" timestamp with time zone default "now"() not null,
    "updated_at" timestamp with time zone default "now"() not null,
    "slug" "text" not null,
    constraint "products_description_check"
        check (("char_length"("description") <= 5000)),
    constraint "products_name_check"
        check ((("char_length"("btrim"("name")) >= 2)
            and ("char_length"("btrim"("name")) <= 160))),
    constraint "products_price_check"
        check (("price" >= (0)::numeric)),
    constraint "products_slug_check"
        check (((("char_length"("slug") >= 2) and ("char_length"("slug") <= 160))
            and ("slug" ~ '^[ა-ჰa-z0-9]+(-[ა-ჰa-z0-9]+)*$'::"text")))
);

alter table "public"."products" owner to "postgres";

alter table only "public"."products"
    add constraint "products_pkey" primary key ("id");

alter table only "public"."products"
    add constraint "products_slug_key" unique ("slug");

-- RESTRICT (not CASCADE): deleting a category that still has products must fail.
-- app/categories/actions.ts maps the resulting 23503 to a user-facing Georgian message.
alter table only "public"."products"
    add constraint "products_category_id_fkey"
    foreign key ("category_id") references "public"."categories"("id")
    on update cascade on delete restrict;

create index if not exists "products_category_id_idx"
    on "public"."products" using "btree" ("category_id");

create index if not exists "products_created_at_idx"
    on "public"."products" using "btree" ("created_at" desc);

-- ===========================================================================
-- schemas/04_category_images.sql
-- ===========================================================================

-- Category image metadata. Bytes live in Cloudflare R2; only the object key is stored.
-- Captured from production 2026-09-11.

create table if not exists "public"."category_images" (
    "id" "uuid" default "gen_random_uuid"() not null,
    "category_id" "uuid" not null,
    "object_key" "text" not null,
    "original_name" "text" not null,
    "content_type" "text" not null,
    "size_bytes" bigint not null,
    "sort_order" integer default 0 not null,
    "created_at" timestamp with time zone default "now"() not null,
    constraint "category_images_content_type_check"
        check (("content_type" = any (array[
            'image/jpeg'::"text", 'image/png'::"text", 'image/webp'::"text"]))),
    -- Enforces the R2 layout: categories/<category-uuid>/<file-uuid>.<ext>
    constraint "category_images_object_key_check"
        check (("object_key" ~ '^categories/[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}/[0-9a-f-]+\.(jpg|jpeg|png|webp)$'::"text")),
    constraint "category_images_size_check"
        check ((("size_bytes" > 0) and ("size_bytes" <= 5242880))),
    constraint "category_images_sort_order_check"
        check (("sort_order" >= 0))
);

alter table "public"."category_images" owner to "postgres";

alter table only "public"."category_images"
    add constraint "category_images_pkey" primary key ("id");

alter table only "public"."category_images"
    add constraint "category_images_object_key_key" unique ("object_key");

-- CASCADE: deleting a category removes its image rows. The R2 objects are deleted
-- separately, best-effort, by the admin's deleteCategory server action.
alter table only "public"."category_images"
    add constraint "category_images_category_id_fkey"
    foreign key ("category_id") references "public"."categories"("id")
    on update cascade on delete cascade;

create index if not exists "category_images_category_id_sort_order_idx"
    on "public"."category_images" using "btree" ("category_id", "sort_order", "created_at");

-- ===========================================================================
-- schemas/05_product_images.sql
-- ===========================================================================

-- Product image metadata. Bytes live in Cloudflare R2; only the object key is stored.
-- Captured from production 2026-09-11.

create table if not exists "public"."product_images" (
    "id" "uuid" default "gen_random_uuid"() not null,
    "product_id" "uuid" not null,
    "object_key" "text" not null,
    "original_name" "text" not null,
    "content_type" "text" not null,
    "size_bytes" bigint not null,
    "sort_order" integer default 0 not null,
    "created_at" timestamp with time zone default "now"() not null,
    constraint "product_images_content_type_check"
        check (("content_type" = any (array[
            'image/jpeg'::"text", 'image/png'::"text", 'image/webp'::"text"]))),
    -- Enforces the R2 layout: products/<product-uuid>/<file-uuid>.<ext>
    constraint "product_images_object_key_check"
        check (("object_key" ~ '^products/[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}/[0-9a-f-]+\.(jpg|jpeg|png|webp)$'::"text")),
    constraint "product_images_size_check"
        check ((("size_bytes" > 0) and ("size_bytes" <= 5242880))),
    constraint "product_images_sort_order_check"
        check (("sort_order" >= 0))
);

alter table "public"."product_images" owner to "postgres";

alter table only "public"."product_images"
    add constraint "product_images_pkey" primary key ("id");

alter table only "public"."product_images"
    add constraint "product_images_object_key_key" unique ("object_key");

-- CASCADE: deleteProduct relies on this. It deletes only the products row and never
-- touches product_images; the cascade removes the metadata rows.
alter table only "public"."product_images"
    add constraint "product_images_product_id_fkey"
    foreign key ("product_id") references "public"."products"("id")
    on update cascade on delete cascade;

create index if not exists "product_images_product_id_sort_order_idx"
    on "public"."product_images" using "btree" ("product_id", "sort_order", "created_at");

-- ===========================================================================
-- schemas/06_contact_rate_limit.sql
-- ===========================================================================

-- Contact-form rate limiting, used by the storefront's /api/contact route.
-- The table lives in the `private` schema so it is not reachable through the Data API;
-- the two SECURITY DEFINER functions are the only way in, and both require a shared
-- secret whose SHA-256 is compared below.
-- Captured from production 2026-09-11.

create table if not exists "private"."contact_email_rate_limits" (
    "client_id" "uuid" not null,
    "send_count" smallint default 0 not null,
    "window_started_at" timestamp with time zone default "clock_timestamp"() not null,
    "updated_at" timestamp with time zone default "clock_timestamp"() not null,
    constraint "contact_email_rate_limits_send_count_check"
        check ((("send_count" >= 0) and ("send_count" <= 3)))
);

alter table "private"."contact_email_rate_limits" owner to "postgres";

alter table only "private"."contact_email_rate_limits"
    add constraint "contact_email_rate_limits_pkey" primary key ("client_id");

alter table "private"."contact_email_rate_limits" enable row level security;

-- Atomically claims one of three sends per 24h window for a client id.
create or replace function "public"."reserve_contact_email_quota"(
    "p_client_id" "uuid", "p_secret" "text")
returns table("allowed" boolean, "remaining" integer, "reset_at" timestamp with time zone)
    language "plpgsql" security definer
    set "search_path" to ''
    as $$
declare
  v_count smallint;
  v_reset_at timestamptz;
begin
  if encode(extensions.digest(p_secret, 'sha256'), 'hex') <>
    '1ed677e15267ec1b462b045e4e1ad29231156695d172bd68c705a41f74188f2e'
  then
    raise exception 'invalid rate limit secret' using errcode = '42501';
  end if;

  insert into private.contact_email_rate_limits as limits (
    client_id,
    send_count,
    window_started_at,
    updated_at
  )
  values (
    p_client_id,
    1,
    clock_timestamp(),
    clock_timestamp()
  )
  on conflict (client_id) do update
  set
    send_count = case
      when limits.window_started_at <= clock_timestamp() - interval '24 hours' then 1
      else limits.send_count + 1
    end,
    window_started_at = case
      when limits.window_started_at <= clock_timestamp() - interval '24 hours' then clock_timestamp()
      else limits.window_started_at
    end,
    updated_at = clock_timestamp()
  where
    limits.window_started_at <= clock_timestamp() - interval '24 hours'
    or limits.send_count < 3
  returning
    limits.send_count,
    limits.window_started_at + interval '24 hours'
  into v_count, v_reset_at;

  if found then
    return query select true, 3 - v_count, v_reset_at;
    return;
  end if;

  select
    limits.send_count,
    limits.window_started_at + interval '24 hours'
  into v_count, v_reset_at
  from private.contact_email_rate_limits as limits
  where limits.client_id = p_client_id;

  return query select false, 0, v_reset_at;
end;
$$;

alter function "public"."reserve_contact_email_quota"(
    "p_client_id" "uuid", "p_secret" "text") owner to "postgres";

-- Gives a reserved send back when the email fails to dispatch.
create or replace function "public"."release_contact_email_quota"(
    "p_client_id" "uuid", "p_secret" "text")
returns "void"
    language "plpgsql" security definer
    set "search_path" to ''
    as $$
begin
  if encode(extensions.digest(p_secret, 'sha256'), 'hex') <>
    '1ed677e15267ec1b462b045e4e1ad29231156695d172bd68c705a41f74188f2e'
  then
    raise exception 'invalid rate limit secret' using errcode = '42501';
  end if;

  update private.contact_email_rate_limits as limits
  set
    send_count = greatest(limits.send_count - 1, 0),
    updated_at = clock_timestamp()
  where
    limits.client_id = p_client_id
    and limits.window_started_at > clock_timestamp() - interval '24 hours'
    and limits.send_count > 0;
end;
$$;

alter function "public"."release_contact_email_quota"(
    "p_client_id" "uuid", "p_secret" "text") owner to "postgres";

revoke all on function "public"."reserve_contact_email_quota"(
    "p_client_id" "uuid", "p_secret" "text") from public;
grant all on function "public"."reserve_contact_email_quota"(
    "p_client_id" "uuid", "p_secret" "text") to "anon";
grant all on function "public"."reserve_contact_email_quota"(
    "p_client_id" "uuid", "p_secret" "text") to "service_role";

revoke all on function "public"."release_contact_email_quota"(
    "p_client_id" "uuid", "p_secret" "text") from public;
grant all on function "public"."release_contact_email_quota"(
    "p_client_id" "uuid", "p_secret" "text") to "anon";
grant all on function "public"."release_contact_email_quota"(
    "p_client_id" "uuid", "p_secret" "text") to "service_role";

-- ===========================================================================
-- schemas/07_grants_and_rls.sql
-- ===========================================================================

-- Table grants and RLS policies for the catalog tables.
-- Captured from production 2026-09-11, EXCEPT where marked DRIFT below.
--
-- Security model: the storefront reads anonymously with the publishable key; the admin
-- writes with a signed-in user's JWT. There is no role or admin table — "authenticated
-- and not anonymous" is treated as "staff". Both apps share this one database.

-- ---------------------------------------------------------------------------
-- Grants
-- ---------------------------------------------------------------------------

grant usage on schema "public" to "postgres";
grant usage on schema "public" to "anon";
grant usage on schema "public" to "authenticated";
grant usage on schema "public" to "service_role";

-- IMPORTANT: every table below is REVOKEd from anon/authenticated before being granted.
--
-- Supabase's database sets ALTER DEFAULT PRIVILEGES on `public` granting anon,
-- authenticated and service_role ALL table privileges (arwdDxtm), so a newly created
-- table starts wide open: `grant select` ADDS to that set and takes nothing away.
-- Without the revokes, anon keeps INSERT/UPDATE/DELETE/TRUNCATE at the privilege layer
-- and RLS is the only thing standing between an anonymous caller and a write. Grants and
-- RLS are meant to be independent layers; the revokes are what make the grants below
-- actually describe the intended state on a fresh database.
--
-- Verified 2026-09-12 on a local stack built from these files: without the revokes,
-- anon held DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on categories,
-- products and product_images.

-- categories
-- DRIFT: production also grants MAINTAIN to anon and authenticated. Omitted here
-- deliberately; see supabase/migrations/*_tighten_image_table_grants.sql.
revoke all on table "public"."categories" from "anon";
revoke all on table "public"."categories" from "authenticated";
grant select on table "public"."categories" to "anon";
grant select, insert, update, delete on table "public"."categories" to "authenticated";
grant all on table "public"."categories" to "service_role";

-- products
revoke all on table "public"."products" from "anon";
revoke all on table "public"."products" from "authenticated";
grant select on table "public"."products" to "anon";
grant select, insert, update, delete on table "public"."products" to "authenticated";
grant all on table "public"."products" to "service_role";

-- product_images
revoke all on table "public"."product_images" from "anon";
revoke all on table "public"."product_images" from "authenticated";
grant select on table "public"."product_images" to "anon";
grant select, insert, update, delete on table "public"."product_images" to "authenticated";
grant all on table "public"."product_images" to "service_role";

-- category_images
-- DRIFT: production currently has `grant all` to BOTH anon and authenticated, which
-- would permit anonymous writes at the privilege layer. RLS is the only thing blocking
-- them today. The corrective migration brings production in line with what is written
-- here — matching product_images above.
revoke all on table "public"."category_images" from "anon";
revoke all on table "public"."category_images" from "authenticated";
grant select on table "public"."category_images" to "anon";
grant select, insert, update, delete on table "public"."category_images" to "authenticated";
grant all on table "public"."category_images" to "service_role";

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------

alter table "public"."categories" enable row level security;
alter table "public"."products" enable row level security;
alter table "public"."category_images" enable row level security;
alter table "public"."product_images" enable row level security;

-- Public reads: the storefront queries these anonymously.
create policy "Categories are publicly readable" on "public"."categories"
    for select to "authenticated", "anon" using (true);

create policy "Products are publicly readable" on "public"."products"
    for select to "authenticated", "anon" using (true);

create policy "Category images are publicly readable" on "public"."category_images"
    for select to "authenticated", "anon" using (true);

create policy "Product images are publicly readable" on "public"."product_images"
    for select to "authenticated", "anon" using (true);

-- Writes: signed-in, non-anonymous users only.
-- `is_anonymous` is checked explicitly because anonymous sign-ins also carry the
-- `authenticated` Postgres role, so `TO authenticated` alone would not exclude them.

create policy "Permanent users can add categories" on "public"."categories"
    for insert to "authenticated"
    with check (((( select "auth"."uid"() as "uid") is not null)
        and (coalesce((((select "auth"."jwt"() as "jwt") ->> 'is_anonymous'::"text"))::boolean, false) = false)));

create policy "Permanent users can edit categories" on "public"."categories"
    for update to "authenticated"
    using (((( select "auth"."uid"() as "uid") is not null)
        and (coalesce((((select "auth"."jwt"() as "jwt") ->> 'is_anonymous'::"text"))::boolean, false) = false)))
    with check (((( select "auth"."uid"() as "uid") is not null)
        and (coalesce((((select "auth"."jwt"() as "jwt") ->> 'is_anonymous'::"text"))::boolean, false) = false)));

create policy "Permanent users can remove categories" on "public"."categories"
    for delete to "authenticated"
    using (((( select "auth"."uid"() as "uid") is not null)
        and (coalesce((((select "auth"."jwt"() as "jwt") ->> 'is_anonymous'::"text"))::boolean, false) = false)));

create policy "Permanent users can add products" on "public"."products"
    for insert to "authenticated"
    with check (((( select "auth"."uid"() as "uid") is not null)
        and (coalesce((((select "auth"."jwt"() as "jwt") ->> 'is_anonymous'::"text"))::boolean, false) = false)));

create policy "Permanent users can edit products" on "public"."products"
    for update to "authenticated"
    using (((( select "auth"."uid"() as "uid") is not null)
        and (coalesce((((select "auth"."jwt"() as "jwt") ->> 'is_anonymous'::"text"))::boolean, false) = false)))
    with check (((( select "auth"."uid"() as "uid") is not null)
        and (coalesce((((select "auth"."jwt"() as "jwt") ->> 'is_anonymous'::"text"))::boolean, false) = false)));

create policy "Permanent users can remove products" on "public"."products"
    for delete to "authenticated"
    using (((( select "auth"."uid"() as "uid") is not null)
        and (coalesce((((select "auth"."jwt"() as "jwt") ->> 'is_anonymous'::"text"))::boolean, false) = false)));

create policy "Permanent users can add category images" on "public"."category_images"
    for insert to "authenticated"
    with check (((( select "auth"."uid"() as "uid") is not null)
        and (coalesce((((select "auth"."jwt"() as "jwt") ->> 'is_anonymous'::"text"))::boolean, false) is false)));

create policy "Permanent users can edit category images" on "public"."category_images"
    for update to "authenticated"
    using (((( select "auth"."uid"() as "uid") is not null)
        and (coalesce((((select "auth"."jwt"() as "jwt") ->> 'is_anonymous'::"text"))::boolean, false) is false)))
    with check (((( select "auth"."uid"() as "uid") is not null)
        and (coalesce((((select "auth"."jwt"() as "jwt") ->> 'is_anonymous'::"text"))::boolean, false) is false)));

create policy "Permanent users can remove category images" on "public"."category_images"
    for delete to "authenticated"
    using (((( select "auth"."uid"() as "uid") is not null)
        and (coalesce((((select "auth"."jwt"() as "jwt") ->> 'is_anonymous'::"text"))::boolean, false) is false)));

create policy "Permanent users can add product images" on "public"."product_images"
    for insert to "authenticated"
    with check (((( select "auth"."uid"() as "uid") is not null)
        and (coalesce((((select "auth"."jwt"() as "jwt") ->> 'is_anonymous'::"text"))::boolean, false) is false)));

create policy "Permanent users can edit product images" on "public"."product_images"
    for update to "authenticated"
    using (((( select "auth"."uid"() as "uid") is not null)
        and (coalesce((((select "auth"."jwt"() as "jwt") ->> 'is_anonymous'::"text"))::boolean, false) is false)))
    with check (((( select "auth"."uid"() as "uid") is not null)
        and (coalesce((((select "auth"."jwt"() as "jwt") ->> 'is_anonymous'::"text"))::boolean, false) is false)));

create policy "Permanent users can remove product images" on "public"."product_images"
    for delete to "authenticated"
    using (((( select "auth"."uid"() as "uid") is not null)
        and (coalesce((((select "auth"."jwt"() as "jwt") ->> 'is_anonymous'::"text"))::boolean, false) is false)));
