-- Step 2 of supabase/SCHEMA_ROADMAP.md: condition aspects, flaws, and image kinds.
--
-- HAND-WRITTEN, not generated by `db diff`, for the same reasons as the step 1 migration:
-- the differ does not reliably capture RLS policies or grants, and this adds several.
--
-- NOT YET APPLIED TO PRODUCTION. Production still does not have the step 1 migration
-- either; see README.md "Known drift" and the reconciliation checklist in the roadmap.
--
-- Adds no NOT NULL column without a default, and backfills nothing, so it is safe to apply
-- to a database with existing rows: every existing product_images row becomes kind
-- 'detail' with no alt text, and no product gains flaws or aspect ratings.

begin;

-- ---------------------------------------------------------------------------
-- condition_aspects — the fixed vocabulary
-- ---------------------------------------------------------------------------

create table if not exists "public"."condition_aspects" (
    "code" "text" not null,
    "sort_order" smallint not null,
    "label_ka" "text" not null,
    "label_en" "text" not null,
    "description_ka" "text" default ''::"text" not null,
    constraint "condition_aspects_code_check"
        check (("code" ~ '^[a-z][a-z0-9_]{1,30}$'::"text")),
    constraint "condition_aspects_sort_order_check"
        check (("sort_order" >= 0)),
    constraint "condition_aspects_label_ka_check"
        check ((("char_length"("btrim"("label_ka")) >= 2)
            and ("char_length"("label_ka") <= 80))),
    constraint "condition_aspects_label_en_check"
        check ((("char_length"("btrim"("label_en")) >= 2)
            and ("char_length"("label_en") <= 80))),
    constraint "condition_aspects_description_ka_check"
        check (("char_length"("description_ka") <= 500))
);

alter table "public"."condition_aspects" owner to "postgres";

alter table only "public"."condition_aspects"
    add constraint "condition_aspects_pkey" primary key ("code");

alter table only "public"."condition_aspects"
    add constraint "condition_aspects_sort_order_key" unique ("sort_order");

insert into "public"."condition_aspects"
    ("code", "sort_order", "label_ka", "label_en", "description_ka")
values
    ('structure',  0, 'კონსტრუქცია',   'Structure',
        'კარკასის სიმტკიცე და მდგრადობა.'),
    ('surface',    1, 'ზედაპირი',       'Surface',
        'ხის, ლაქის ან საღებავის მდგომარეობა — ნაკაწრები, ლაქები, გახუნება.'),
    ('upholstery', 2, 'რბილი ნაწილი',   'Upholstery',
        'ქსოვილი, ტყავი და ბალიშები. ეხება მხოლოდ რბილ ავეჯს.'),
    ('hardware',   3, 'მექანიზმები',     'Hardware',
        'უჯრები, ანჯამები, ბორბლები და სხვა მოძრავი ნაწილები.'),
    ('odour',      4, 'სუნი',            'Odour',
        'უცხო სუნი — თამბაქო, ნესტი, შინაური ცხოველი.')
on conflict ("code") do nothing;

-- ---------------------------------------------------------------------------
-- product_images: kind and alt_text
-- ---------------------------------------------------------------------------

alter table "public"."product_images"
    add column if not exists "kind" "text" default 'detail'::"text" not null,
    add column if not exists "alt_text" "text";

alter table "public"."product_images"
    add constraint "product_images_kind_check"
        check (("kind" = any (array[
            'primary'::"text", 'detail'::"text",
            'flaw'::"text", 'dimension_diagram'::"text"]))),
    add constraint "product_images_alt_text_check"
        check (("char_length"("alt_text") <= 300));

-- ---------------------------------------------------------------------------
-- product_condition_aspects
-- ---------------------------------------------------------------------------

create table if not exists "public"."product_condition_aspects" (
    "product_id" "uuid" not null,
    "aspect_code" "text" not null,
    "grade_code" "text" not null,
    "note" "text",
    "created_at" timestamp with time zone default "now"() not null,
    constraint "product_condition_aspects_note_check"
        check (("char_length"("note") <= 500))
);

alter table "public"."product_condition_aspects" owner to "postgres";

alter table only "public"."product_condition_aspects"
    add constraint "product_condition_aspects_pkey"
    primary key ("product_id", "aspect_code");

alter table only "public"."product_condition_aspects"
    add constraint "product_condition_aspects_product_id_fkey"
    foreign key ("product_id") references "public"."products"("id")
    on update cascade on delete cascade;

alter table only "public"."product_condition_aspects"
    add constraint "product_condition_aspects_aspect_code_fkey"
    foreign key ("aspect_code") references "public"."condition_aspects"("code")
    on update cascade on delete restrict;

alter table only "public"."product_condition_aspects"
    add constraint "product_condition_aspects_grade_code_fkey"
    foreign key ("grade_code") references "public"."condition_grades"("code")
    on update cascade on delete restrict;

create index if not exists "product_condition_aspects_product_id_idx"
    on "public"."product_condition_aspects" using "btree" ("product_id");

-- ---------------------------------------------------------------------------
-- product_flaws
-- ---------------------------------------------------------------------------

create table if not exists "public"."product_flaws" (
    "id" "uuid" default "gen_random_uuid"() not null,
    "product_id" "uuid" not null,
    "image_id" "uuid",
    "flaw_type" "text" not null,
    "severity" "text" not null,
    "location_ka" "text",
    "note_ka" "text" not null,
    "sort_order" integer default 0 not null,
    "created_at" timestamp with time zone default "now"() not null,
    constraint "product_flaws_flaw_type_check"
        check (("flaw_type" = any (array[
            'scratch'::"text", 'dent'::"text", 'stain'::"text", 'chip'::"text",
            'crack'::"text", 'fade'::"text", 'wear'::"text", 'odour'::"text",
            'missing_part'::"text", 'repair'::"text", 'other'::"text"]))),
    constraint "product_flaws_severity_check"
        check (("severity" = any (array[
            'minor'::"text", 'moderate'::"text", 'significant'::"text"]))),
    constraint "product_flaws_location_ka_check"
        check (("char_length"("location_ka") <= 160)),
    constraint "product_flaws_note_ka_check"
        check ((("char_length"("btrim"("note_ka")) >= 2)
            and ("char_length"("note_ka") <= 500))),
    constraint "product_flaws_sort_order_check"
        check (("sort_order" >= 0))
);

alter table "public"."product_flaws" owner to "postgres";

alter table only "public"."product_flaws"
    add constraint "product_flaws_pkey" primary key ("id");

alter table only "public"."product_flaws"
    add constraint "product_flaws_product_id_fkey"
    foreign key ("product_id") references "public"."products"("id")
    on update cascade on delete cascade;

-- SET NULL, not CASCADE: deleting a photo must not delete the flaw it documented.
alter table only "public"."product_flaws"
    add constraint "product_flaws_image_id_fkey"
    foreign key ("image_id") references "public"."product_images"("id")
    on update cascade on delete set null;

create index if not exists "product_flaws_product_id_sort_order_idx"
    on "public"."product_flaws" using "btree" ("product_id", "sort_order", "created_at");

create index if not exists "product_flaws_image_id_idx"
    on "public"."product_flaws" using "btree" ("image_id")
    where ("image_id" is not null);

-- ---------------------------------------------------------------------------
-- Grants and RLS
-- ---------------------------------------------------------------------------

-- Revoked before granting: Supabase's default privileges leave a new table wide open to
-- anon, and `grant select` alone adds without taking away. See schemas/07_grants_and_rls.sql.
revoke all on table "public"."condition_aspects" from "anon";
revoke all on table "public"."condition_aspects" from "authenticated";
grant select on table "public"."condition_aspects" to "anon";
grant select, insert, update, delete on table "public"."condition_aspects" to "authenticated";
grant all on table "public"."condition_aspects" to "service_role";

revoke all on table "public"."product_condition_aspects" from "anon";
revoke all on table "public"."product_condition_aspects" from "authenticated";
grant select on table "public"."product_condition_aspects" to "anon";
grant select, insert, update, delete on table "public"."product_condition_aspects" to "authenticated";
grant all on table "public"."product_condition_aspects" to "service_role";

revoke all on table "public"."product_flaws" from "anon";
revoke all on table "public"."product_flaws" from "authenticated";
grant select on table "public"."product_flaws" to "anon";
grant select, insert, update, delete on table "public"."product_flaws" to "authenticated";
grant all on table "public"."product_flaws" to "service_role";

alter table "public"."condition_aspects" enable row level security;
alter table "public"."product_condition_aspects" enable row level security;
alter table "public"."product_flaws" enable row level security;

create policy "Condition aspects are publicly readable" on "public"."condition_aspects"
    for select to "authenticated", "anon" using (true);

-- The products read policy hides draft/archived rows but does NOT cascade to child
-- tables. Without these EXISTS checks, a draft product's flaws would be readable with the
-- publishable key even though the product itself is not.
create policy "Condition aspects of visible products are readable"
    on "public"."product_condition_aspects"
    for select to "authenticated", "anon"
    using (exists (
        select 1 from "public"."products" "p"
        where "p"."id" = "product_condition_aspects"."product_id"
    ));

create policy "Flaws of visible products are readable" on "public"."product_flaws"
    for select to "authenticated", "anon"
    using (exists (
        select 1 from "public"."products" "p"
        where "p"."id" = "product_flaws"."product_id"
    ));

create policy "Permanent users can add condition aspects" on "public"."condition_aspects"
    for insert to "authenticated"
    with check (((( select "auth"."uid"() as "uid") is not null)
        and (coalesce((((select "auth"."jwt"() as "jwt") ->> 'is_anonymous'::"text"))::boolean, false) = false)));

create policy "Permanent users can edit condition aspects" on "public"."condition_aspects"
    for update to "authenticated"
    using (((( select "auth"."uid"() as "uid") is not null)
        and (coalesce((((select "auth"."jwt"() as "jwt") ->> 'is_anonymous'::"text"))::boolean, false) = false)))
    with check (((( select "auth"."uid"() as "uid") is not null)
        and (coalesce((((select "auth"."jwt"() as "jwt") ->> 'is_anonymous'::"text"))::boolean, false) = false)));

create policy "Permanent users can remove condition aspects" on "public"."condition_aspects"
    for delete to "authenticated"
    using (((( select "auth"."uid"() as "uid") is not null)
        and (coalesce((((select "auth"."jwt"() as "jwt") ->> 'is_anonymous'::"text"))::boolean, false) = false)));

create policy "Permanent users can add product condition aspects"
    on "public"."product_condition_aspects"
    for insert to "authenticated"
    with check (((( select "auth"."uid"() as "uid") is not null)
        and (coalesce((((select "auth"."jwt"() as "jwt") ->> 'is_anonymous'::"text"))::boolean, false) = false)));

create policy "Permanent users can edit product condition aspects"
    on "public"."product_condition_aspects"
    for update to "authenticated"
    using (((( select "auth"."uid"() as "uid") is not null)
        and (coalesce((((select "auth"."jwt"() as "jwt") ->> 'is_anonymous'::"text"))::boolean, false) = false)))
    with check (((( select "auth"."uid"() as "uid") is not null)
        and (coalesce((((select "auth"."jwt"() as "jwt") ->> 'is_anonymous'::"text"))::boolean, false) = false)));

create policy "Permanent users can remove product condition aspects"
    on "public"."product_condition_aspects"
    for delete to "authenticated"
    using (((( select "auth"."uid"() as "uid") is not null)
        and (coalesce((((select "auth"."jwt"() as "jwt") ->> 'is_anonymous'::"text"))::boolean, false) = false)));

create policy "Permanent users can add product flaws" on "public"."product_flaws"
    for insert to "authenticated"
    with check (((( select "auth"."uid"() as "uid") is not null)
        and (coalesce((((select "auth"."jwt"() as "jwt") ->> 'is_anonymous'::"text"))::boolean, false) = false)));

create policy "Permanent users can edit product flaws" on "public"."product_flaws"
    for update to "authenticated"
    using (((( select "auth"."uid"() as "uid") is not null)
        and (coalesce((((select "auth"."jwt"() as "jwt") ->> 'is_anonymous'::"text"))::boolean, false) = false)))
    with check (((( select "auth"."uid"() as "uid") is not null)
        and (coalesce((((select "auth"."jwt"() as "jwt") ->> 'is_anonymous'::"text"))::boolean, false) = false)));

create policy "Permanent users can remove product flaws" on "public"."product_flaws"
    for delete to "authenticated"
    using (((( select "auth"."uid"() as "uid") is not null)
        and (coalesce((((select "auth"."jwt"() as "jwt") ->> 'is_anonymous'::"text"))::boolean, false) = false)));

commit;
